# Generated by Django 4.1.6 on 2023-06-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_user_is_credential_form_user_is_credential_report_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_customer",
            field=models.BooleanField(default=False),
        ),
    ]
